apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: "2024-03-20T09:17:10Z"
  name: secret-access-cr
  resourceVersion: "14604"
  uid: c3824d1f-315f-41cf-9a70-06417f874c51
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
