apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    creationTimestamp: "2024-03-20T09:23:47Z"
    name: secret-rb
    namespace: default
    resourceVersion: "14724"
    uid: 0fcc585e-5c62-40d4-a329-c78c808e76c2
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: secret-access-cr
  subjects:
  - kind: ServiceAccount
    name: secret-access-sa
kind: List
metadata:
  resourceVersion: ""
