apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from: 
    - podSelector: {}
    ports:
    - port: 80
      protocol: TCP
    #  - Egress
