apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-rb
  namespace: default
subjects:
- kind: ServiceAccount
  name: secret-access-sa # "name" is case sensitive
roleRef:
  kind: ClusterRole #this must be Role or ClusterRole
  name: secret-access-cr # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
