apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: secondapp
  name: secondapp
spec:
  serviceAccountName: secret-access-sa
    #securityContext:
    #    runAsUser: 1000
  containers:
  - name: webserver
    image: nginx
  - image: busybox
    name: secondapp
    command:
      - sleep
      - "3600"
    resources: {}
    securityContext: 
      runAsUser: 2000
      allowPrivilegeEscalation: false
      capabilities:
        add: ["NET_ADMIN", "SYS_TIME"]
    volumeMounts:
    - name: mysql
      mountPath: /mysqlpassword
  volumes:
  - name: mysql
    secret:
      secretName: lfsecret
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
