apiVersion: v1
data:
  password: bWF5dXI=
kind: Secret
metadata:
  creationTimestamp: "2024-03-20T09:03:50Z"
  name: lfsecret
  namespace: default
  resourceVersion: "14348"
  uid: b6689a59-1e0d-4556-87bc-0134c8ce8984
type: Opaque
