apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    type: webserver
  name: basic2
spec:
  containers:
  - image: nginx
    name: basic2
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
