apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    type: multi
  name: multi
spec:
  containers:
  - image: nginx
    name: webserver
    ports:
    - containerPort: 80
  - image: fluentd
    name: fdlogger
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
