apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: init
spec:
  containers:
  - image: nginx
    name: init
    resources: {}
  initContainers:
  - name: init-container
    image: busybox
    command: ['sh', '-c', 'echo Initializing... & sleep 10']
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
