apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: stress
  name: stress
spec:
  containers:
  - args:
    - -cpus
    - "2"
    - -mem-total
    - 1000Mi
    - -mem-alloc-size
    - 100Mi
    image: vish/stress
    name: stress
    resources: 
      limits:
        cpu: "2"
        memory: "2000Mi"
      requests:
        cpu: "0.5"
        memory: "100Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
