apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: stress
  name: stress
spec:
  containers:
  - image: vish/stress
    name: stress
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 0.5
        memory: 500Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
